name: action-label-manager
description: Sync GitHub Labels.
inputs:
  access-token:
    description: GitHub access token to sync labels (`repo` scope required).
    required: true
  target-repository:
    default: ${{ github.repository }}
    description: GitHub repository where labels are synced. Defaults to the current repository.
    required: false
  labels-file:
    default: ""
    description: Path to a custom labels file (default is `labels.json` in the action directory).
    required: false
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install Dependencies
      run: npm install -g github-label-sync
      shell: bash
    - name: Run Action
      env:
        GITHUB_TOKEN: ${{ inputs.access-token }}
        REPOSITORY: ${{ inputs.target-repository }}
        LABELS_FILE: ${{ inputs.labels-file }}
        DEFAULT_LABELS_FILE: ${{ github.action_path }}/labels.json
      run: node ${{ github.action_path }}/action.js
      shell: bash
