name: action-label-manager
description: Sync GitHub Labels.
inputs:
  access-token:
    description: GitHub access token to sync labels (`repo` scope required).
    required: true
  target-repository:
    default: ${{ github.repository }}
    description: GitHub repository where labels are synced. Defaults to the current repository.
    required: false
  labels-file:
    default: ""
    description: Path to a custom labels file (default is `labels.json` in the action directory).
    required: false
runs:
  using: 'node22'
  main: 'action.js'
