name: action-label-manager
description: Sync GitHub Labels.
inputs:
  access-token:
    description: GitHub access token to sync labels (`repo` scope required).
    required: true
  target-repository:
    default: ${{ github.repository }}
    description: GitHub repository where labels are synced. Defaults to the current repository.
    required: false
  labels-file:
    default: ""
    description: Path to a custom labels file (default is `labels.json` in the action directory).
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install -g github-label-sync
      shell: bash
    - run: |
        {
          echo "Syncing labels from ${{ inputs.labels-file }} to ${{ inputs.target-repository }}"
          if [ -n "${{ inputs.labels-file }}" ]; then
            npx github-label-sync \
            --access-token ${{ inputs.access-token }} \
            --labels ${{ inputs.labels-file }} \
            ${{ inputs.target-repository }}
            echo "Labels synced from custom file: ${{ inputs.labels-file }}"
          fi
        } || {
          echo "Syncing labels from default labels file to ${{ inputs.target-repository }}"
          npx github-label-sync \
          --access-token ${{ inputs.access-token }} \
          --labels ${{ github.action_path }}/labels.json \
          ${{ inputs.target-repository }}
          echo "Labels synced from default labels file"
        }
      shell: bash
