name: Test Action
permissions: read-all
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
    update-labels:
        runs-on: ubuntu-latest
        name: Update Labels
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Update Labels
            uses: ./
            id: updatelabels
            with:
              github-token: ${{ secrets.LABEL_TOKEN }}