name: Test
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test-action:
    permissions:
        issues: write
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set Labels
        uses: ./
        id: set-labels
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          labels-file: labels.json
